import type { SettingDefinition, SeedSettingsPreset } from '../seed-settings-types';

export const availableSettings: SettingDefinition[] = [
  // Requirements
  { key: 'Seed', category: 'Requirements', type: 'number' },
  { key: 'Logic Type', category: 'Requirements', type: 'string', options: [
    { value: 'Glitchless Logic', label: 'Glitchless Logic' },
    { value: 'Advanced Glitchless Logic', label: 'Advanced Glitchless Logic' },
    { value: 'Glitched Logic', label: 'Glitched Logic' },
    { value: 'Minimal Logic', label: 'Minimal Logic' },
    { value: 'No Logic', label: 'No Logic' },
  ] },
  { key: 'Maximum B Locker', category: 'Requirements', type: 'number' },
  { key: 'Maximum B Locker ensured', category: 'Requirements', type: 'boolean' },
  { key: 'Maximum Troff N Scoff', category: 'Requirements', type: 'number' },
  { key: 'Hard Troff N Scoff', category: 'Requirements', type: 'boolean' },
  { key: 'Chaos B.Lockers', category: 'Requirements', type: 'boolean' },
  { key: 'Open Lobbies', category: 'Requirements', type: 'boolean' },
  { key: 'Smaller Shops', category: 'Requirements', type: 'boolean' },
  { key: 'Galleon Water Level', category: 'Requirements', type: 'string', options: [
    { value: 'lowered', label: 'Lowered' },
    { value: 'raised', label: 'Raised' },
    { value: 'random', label: 'Random' },
  ] },
  { key: 'Fungi Time of Day', category: 'Requirements', type: 'string', options: [
    { value: 'day', label: 'Day' },
    { value: 'night', label: 'Night' },
    { value: 'dusk', label: 'Dusk' },
    { value: 'progressive', label: 'Progressive' },
    { value: 'random', label: 'Random' },
  ] },
  { key: 'Random Shop Prices', category: 'Requirements', type: 'string', options: [
    { value: 'vanilla', label: 'Vanilla' },
    { value: 'free', label: 'Free' },
    { value: 'low', label: 'Low' },
    { value: 'medium', label: 'Medium' },
    { value: 'high', label: 'High' },
    { value: 'extreme', label: 'Extreme' },
  ] },
  { key: 'Activated Warps', category: 'Requirements', type: 'string', options: [
    { value: 'off', label: 'Off' },
    { value: 'isles', label: 'Isles' },
    { value: 'isles_inc_helm_lobby', label: 'Isles + Helm Lobby' },
    { value: 'all', label: 'All' },
  ] },
  { key: 'Fairies Required for Rareware GB', category: 'Requirements', type: 'number' },
  { key: 'Pearls Required for Mermaid GB', category: 'Requirements', type: 'number' },
  { key: 'Random Jetpac Medal Requirement', category: 'Requirements', type: 'boolean' },

  // Progression
  { key: 'Win Condition', category: 'Progression', type: 'string', options: [
    { value: '8 Keys', label: '8 Keys' },
    { value: 'Get the Last Key', label: 'Get the Last Key' },
    { value: 'All Fairies', label: 'All Fairies' },
    { value: 'All Blueprints', label: 'All Blueprints' },
    { value: 'All Medals', label: 'All Medals' },
    { value: 'Poke Snap', label: 'Poke Snap' },
    { value: 'Beat K. Rool', label: 'Beat K. Rool' },
  ] },
  { key: 'Random Win Condition', category: 'Progression', type: 'boolean' },
  { key: 'Select Starting Keys', category: 'Progression', type: 'boolean' },
  { key: 'Number of Keys Pregiven', category: 'Progression', type: 'number' },
  { key: 'Key 8 in Helm', category: 'Progression', type: 'boolean' },
  { key: 'Helm Setting', category: 'Progression', type: 'string', options: [
    { value: 'default', label: 'Default' },
    { value: 'skip_start', label: 'Skip Start' },
    { value: 'skip_all', label: 'Skip All' },
  ] },
  { key: 'Helm Room Bonus Count', category: 'Progression', type: 'number' },
  { key: 'Crown Door Open', category: 'Progression', type: 'boolean' },
  { key: 'Coin Door Open', category: 'Progression', type: 'boolean' },
  { key: 'Chunky Phase Slam Requirement', category: 'Progression', type: 'string', options: [
    { value: 'green', label: 'Base Slam' },
    { value: 'blue', label: 'Super Slam' },
    { value: 'red', label: 'Super Duper Slam' },
    { value: 'random', label: 'Random Slam' },
  ] },

  // Overworld
  { key: 'Shuffle Enemies', category: 'Overworld', type: 'boolean' },
  { key: 'Puzzle Randomization', category: 'Overworld', type: 'string', options: [
    { value: 'off', label: 'Off' },
    { value: 'easy', label: 'Easy' },
    { value: 'medium', label: 'Medium' },
    { value: 'hard', label: 'Hard' },
    { value: 'chaos', label: 'Chaos' },
  ] },
  { key: 'Mirror Mode', category: 'Overworld', type: 'boolean' },
  { key: 'Crown Enemy Rando', category: 'Overworld', type: 'string', options: [
    { value: 'vanilla', label: 'Vanilla' },
    { value: 'easy', label: 'Easy' },
    { value: 'medium', label: 'Medium' },
    { value: 'hard', label: 'Hard' },
    { value: 'progressive', label: 'Progressive' },
  ] },
  { key: 'Shuffled Bananaport Levels', category: 'Overworld', type: 'boolean' },
  { key: 'Loading Zones Shuffled', category: 'Overworld', type: 'string', options: [
    { value: 'none', label: 'None' },
    { value: 'levels', label: 'Levels' },
    { value: 'all', label: 'All' },
  ] },
  { key: 'Decoupled Loading Zones', category: 'Overworld', type: 'boolean' },
  { key: 'Helm Location Shuffled', category: 'Overworld', type: 'boolean' },
  { key: 'Complex Level Order', category: 'Overworld', type: 'boolean' },
  { key: 'Banana Port Randomization', category: 'Overworld', type: 'string', options: [
    { value: 'off', label: 'Off' },
    { value: 'in_level', label: 'In Level' },
    { value: 'crossmap_coupled', label: 'Cross Map Coupled' },
    { value: 'crossmap_decoupled', label: 'Cross Map Decoupled' },
  ] },
  { key: 'Banana port Location Shuffle', category: 'Overworld', type: 'string', options: [
    { value: 'off', label: 'Off' },
    { value: 'vanilla_only', label: 'Vanilla Only' },
    { value: 'half_vanilla', label: 'Half Vanilla' },
    { value: 'on', label: 'On' },
  ] },
  { key: 'Randomize CB Locations', category: 'Overworld', type: 'boolean' },
  { key: 'Randomize Kasplats', category: 'Overworld', type: 'string', options: [
    { value: 'off', label: 'Off' },
    { value: 'vanilla_locations', label: 'Vanilla Locations' },
    { value: 'location_shuffle', label: 'Location Shuffle' },
  ] },
  { key: 'Randomize Banana Fairies', category: 'Overworld', type: 'boolean' },
  { key: 'Randomize Battle Arenas', category: 'Overworld', type: 'boolean' },
  { key: 'Randomize Shop Locations', category: 'Overworld', type: 'boolean' },
  { key: 'Randomize Coin Locations', category: 'Overworld', type: 'boolean' },
  { key: 'Randomize Pickups', category: 'Overworld', type: 'boolean' },
  { key: 'Randomize Patches', category: 'Overworld', type: 'boolean' },
  { key: 'Randomize Crates', category: 'Overworld', type: 'boolean' },
  { key: 'Vanilla Door Shuffle', category: 'Overworld', type: 'boolean' },
  { key: "Dos' Doors", category: 'Overworld', type: 'boolean' },
  { key: 'Randomize Wrinkly Doors', category: 'Overworld', type: 'boolean' },
  { key: 'Randomize T&S Portals', category: 'Overworld', type: 'boolean' },
  { key: 'Switchsanity', category: 'Overworld', type: 'boolean' },
  { key: 'Progressive Switch Strength', category: 'Overworld', type: 'boolean' },
  { key: 'Auto Complete Bonus Barrels', category: 'Overworld', type: 'boolean' },
  { key: 'Hard Mode Enabled', category: 'Overworld', type: 'boolean' },
  { key: 'Hard Bosses Enabled', category: 'Overworld', type: 'boolean' },
  { key: 'Irondonk', category: 'Overworld', type: 'boolean' },
  { key: 'Damage Amount', category: 'Overworld', type: 'string', options: [
    { value: 'default', label: 'Default' },
    { value: 'double', label: 'Double' },
    { value: 'quad', label: 'Quad' },
    { value: 'ohko', label: 'OHKO' },
  ] },

  // Items
  { key: 'Ice Traps Damage Player', category: 'Items', type: 'boolean' },
  { key: 'Starting Moves Count', category: 'Items', type: 'number' },
  { key: 'Free Trade Agreement', category: 'Items', type: 'boolean' },

  // Quality of Life
  { key: 'Dim Solved Hints', category: 'Quality of Life', type: 'boolean' },
  { key: 'No Joke Hints', category: 'Quality of Life', type: 'boolean' },
  { key: 'Kongless Hint Doors', category: 'Quality of Life', type: 'boolean' },
  { key: 'Item Reward Previews', category: 'Quality of Life', type: 'boolean' },
  { key: 'Hint Preset', category: 'Quality of Life', type: 'string', options: [
    { value: 'Standard', label: 'Standard' },
    { value: 'Cryptic', label: 'Cryptic' },
    { value: 'Item Hinting', label: 'Item Hinting' },
    { value: 'Advanced Item Hinting', label: 'Advanced Item Hinting' },
    { value: 'Off', label: 'Off' },
  ] },
  { key: 'Progressive Hint Item', category: 'Quality of Life', type: 'string', options: [
    { value: 'off', label: 'Off' },
    { value: 'req_gb', label: 'Golden Banana' },
    { value: 'req_bp', label: 'Blueprint' },
    { value: 'req_key', label: 'Key' },
    { value: 'req_medal', label: 'Medal' },
    { value: 'req_crown', label: 'Crown' },
    { value: 'req_fairy', label: 'Fairy' },
    { value: 'req_rainbowcoin', label: 'Rainbow Coin' },
    { value: 'req_pearl', label: 'Pearl' },
    { value: 'req_cb', label: 'Colored Banana' },
  ] },
  { key: 'Progressive Hint Cap', category: 'Quality of Life', type: 'number' },
];

export const defaultSettings: string[] = [
  'Seed',
  'Logic Type',
  'Win Condition',
  'Helm Setting',
  'Maximum B Locker',
  'Maximum Troff N Scoff',
  'Loading Zones Shuffled',
  'Free Trade Agreement',
  'Number of Keys Pregiven',
  'Key 8 in Helm',
  'Crown Door Open',
  'Coin Door Open',
  "Dos' Doors",
  'Auto Complete Bonus Barrels',
  'Fairies Required for Rareware GB',
  'Pearls Required for Mermaid GB',
  'Item Reward Previews',
];

export const settingsPresets: SeedSettingsPreset[] = [
  {
    name: 'Season 4',
    description: 'Standard S4 race settings',
    selectedKeys: [
      ...defaultSettings,
      'Helm Room Bonus Count',
      'Complex Level Order',
      'Smaller Shops',
      'Galleon Water Level',
      'Fungi Time of Day',
      'Random Shop Prices',
      'Activated Warps',
      'Switchsanity',
      'Progressive Switch Strength',
      'Vanilla Door Shuffle',
      'Randomize Wrinkly Doors',
      'Randomize T&S Portals',
      'Kongless Hint Doors',
      'Hint Preset',
      'Puzzle Randomization',
      'Crown Enemy Rando',
    ],
    values: {
      'Logic Type': 'Glitchless Logic',
      'Win Condition': '8 Keys',
      'Helm Setting': 'skip_start',
      'Helm Room Bonus Count': 1,
      'Maximum B Locker': 50,
      'Maximum Troff N Scoff': 150,
      'Loading Zones Shuffled': 'levels',
      'Complex Level Order': true,
      'Free Trade Agreement': true,
      'Number of Keys Pregiven': 2,
      'Key 8 in Helm': true,
      'Crown Door Open': true,
      'Coin Door Open': false,
      "Dos' Doors": true,
      'Auto Complete Bonus Barrels': false,
      'Fairies Required for Rareware GB': 6,
      'Pearls Required for Mermaid GB': 1,
      'Item Reward Previews': true,
      'Smaller Shops': true,
      'Galleon Water Level': 'raised',
      'Fungi Time of Day': 'night',
      'Random Shop Prices': 'medium',
      'Activated Warps': 'isles_inc_helm_lobby',
      'Switchsanity': true,
      'Progressive Switch Strength': true,
      'Vanilla Door Shuffle': true,
      'Randomize Wrinkly Doors': true,
      'Randomize T&S Portals': true,
      'Kongless Hint Doors': true,
      'Hint Preset': 'Standard',
      'Puzzle Randomization': 'medium',
      'Crown Enemy Rando': 'easy',
    },
  },
  {
    name: 'Season 4.5',
    description: 'Standard S4.5 race settings',
    selectedKeys: [
      ...defaultSettings,
      'Helm Room Bonus Count',
      'Complex Level Order',
      'Smaller Shops',
      'Galleon Water Level',
      'Fungi Time of Day',
      'Random Shop Prices',
      'Activated Warps',
      'Switchsanity',
      'Progressive Switch Strength',
      'Vanilla Door Shuffle',
      'Randomize Wrinkly Doors',
      'Randomize T&S Portals',
      'Kongless Hint Doors',
      'Hint Preset',
      'Progressive Hint Item',
      'Progressive Hint Cap',
      'Puzzle Randomization',
      'Crown Enemy Rando',
    ],
    values: {
      'Logic Type': 'Glitchless Logic',
      'Win Condition': '8 Keys',
      'Helm Setting': 'skip_start',
      'Helm Room Bonus Count': 1,
      'Maximum B Locker': 50,
      'Maximum Troff N Scoff': 150,
      'Loading Zones Shuffled': 'levels',
      'Complex Level Order': true,
      'Free Trade Agreement': true,
      'Number of Keys Pregiven': 2,
      'Key 8 in Helm': true,
      'Crown Door Open': true,
      'Coin Door Open': false,
      "Dos' Doors": true,
      'Auto Complete Bonus Barrels': false,
      'Fairies Required for Rareware GB': 6,
      'Pearls Required for Mermaid GB': 1,
      'Item Reward Previews': true,
      'Smaller Shops': true,
      'Galleon Water Level': 'raised',
      'Fungi Time of Day': 'night',
      'Random Shop Prices': 'medium',
      'Activated Warps': 'isles_inc_helm_lobby',
      'Switchsanity': true,
      'Progressive Switch Strength': true,
      'Vanilla Door Shuffle': true,
      'Randomize Wrinkly Doors': true,
      'Randomize T&S Portals': true,
      'Kongless Hint Doors': true,
      'Hint Preset': 'Standard',
      'Progressive Hint Item': 'req_crown',
      'Progressive Hint Cap': 55,
      'Puzzle Randomization': 'medium',
      'Crown Enemy Rando': 'easy',
    },
  },
  {
    name: 'Balanced LZR',
    description: 'Balanced Loading Zone Randomizer settings',
    selectedKeys: [
      ...defaultSettings,
      'Helm Room Bonus Count',
      'Decoupled Loading Zones',
      'Helm Location Shuffled',
      'Smaller Shops',
      'Galleon Water Level',
      'Fungi Time of Day',
      'Random Shop Prices',
      'Activated Warps',
      'Progressive Switch Strength',
      'Hint Preset',
      'Progressive Hint Item',
      'Progressive Hint Cap',
      'Puzzle Randomization',
      'Crown Enemy Rando',
    ],
    values: {
      'Logic Type': 'Glitchless Logic',
      'Win Condition': '8 Keys',
      'Helm Setting': 'skip_start',
      'Helm Room Bonus Count': 0,
      'Maximum B Locker': 0,
      'Maximum Troff N Scoff': 0,
      'Loading Zones Shuffled': 'all',
      'Decoupled Loading Zones': false,
      'Helm Location Shuffled': true,
      'Free Trade Agreement': true,
      'Number of Keys Pregiven': 3,
      'Key 8 in Helm': true,
      'Crown Door Open': false,
      'Coin Door Open': true,
      "Dos' Doors": false,
      'Auto Complete Bonus Barrels': true,
      'Fairies Required for Rareware GB': 4,
      'Pearls Required for Mermaid GB': 1,
      'Item Reward Previews': true,
      'Smaller Shops': true,
      'Galleon Water Level': 'lowered',
      'Fungi Time of Day': 'dusk',
      'Random Shop Prices': 'medium',
      'Activated Warps': 'isles',
      'Progressive Switch Strength': true,
      'Hint Preset': 'Standard',
      'Progressive Hint Item': 'req_gb',
      'Progressive Hint Cap': 50,
      'Puzzle Randomization': 'medium',
      'Crown Enemy Rando': 'easy',
    },
  },
  {
    name: 'Kevin 5.0',
    description: 'Kevin 5.0 settings',
    selectedKeys: [
      ...defaultSettings,
      'Helm Room Bonus Count',
      'Complex Level Order',
      'Helm Location Shuffled',
      'Smaller Shops',
      'Galleon Water Level',
      'Fungi Time of Day',
      'Random Shop Prices',
      'Activated Warps',
      'Switchsanity',
      'Progressive Switch Strength',
      'Randomize T&S Portals',
      'Hint Preset',
      'Progressive Hint Item',
      'Progressive Hint Cap',
      'Puzzle Randomization',
      'Crown Enemy Rando',
    ],
    values: {
      'Logic Type': 'Advanced Glitchless Logic',
      'Win Condition': '8 Keys',
      'Helm Setting': 'skip_start',
      'Helm Room Bonus Count': 1,
      'Maximum B Locker': 60,
      'Maximum Troff N Scoff': 0,
      'Loading Zones Shuffled': 'levels',
      'Complex Level Order': true,
      'Helm Location Shuffled': true,
      'Free Trade Agreement': true,
      'Number of Keys Pregiven': 2,
      'Key 8 in Helm': false,
      'Crown Door Open': true,
      'Coin Door Open': true,
      "Dos' Doors": false,
      'Auto Complete Bonus Barrels': false,
      'Fairies Required for Rareware GB': 5,
      'Pearls Required for Mermaid GB': 2,
      'Item Reward Previews': true,
      'Smaller Shops': true,
      'Galleon Water Level': 'raised',
      'Fungi Time of Day': 'dusk',
      'Random Shop Prices': 'medium',
      'Activated Warps': 'isles',
      'Switchsanity': true,
      'Progressive Switch Strength': true,
      'Randomize T&S Portals': true,
      'Hint Preset': 'Standard',
      'Progressive Hint Item': 'req_gb',
      'Progressive Hint Cap': 50,
      'Puzzle Randomization': 'medium',
      'Crown Enemy Rando': 'progressive',
    },
  },
];
